name: mcslopes
channels:
  - rapidsai
  - conda-forge
  - nvidia
  - numba
  - defaults
dependencies:
  - python==3.11
  - pip
  - numba
  - icc_rt
  - numpy
  - scipy
  - matplotlib
  - cupy
  - cuda-version==11.8
  - ipython
  - jupyter
  - pylops
  - pip:
    - pyyaml
