name: mcslopes
channels:
  - defaults
  - conda-forge
  - numba
dependencies:
  - python>=3.8
  - pip
  - numba==0.55.2
  - icc_rt
  - numpy
  - scipy
  - matplotlib
  - ipython
  - jupyter
  - pylops