exp:
  label: gom # dataset label
  number: 1 # experiment number
  name: GOM - Slopes interpolation with 1st order gradient # experiment name
  inputfile: ../../data/gom_data_sub5.npz # input file with subsampled data
  truefile: ../../data/gom_data_forsub5.npz # input file with finely sampled data for debugging purposes (leave empty if not available)

global:
  USE_CUPY: True # use cupy or not

subsampling:
  nsub: 5 # subsampling factor (make sure it agrees with the data)

preprocessing:
  apply_nmo: True # apply NMO correction prior to interpolation (True) or not (False)
  vnmo: 1500 # NMO velocity (in m/s)
  mask_thresh: 0.1 # time-space mask threshold
  nfft_t: 2048  # lenght of frequency axis (used to compute gradients and perform FK transforms during data reconstruction)
  nfft_x: 512 # lenght of wavenumber axis (used to compute gradients and perform FK transforms during data reconstruction)

fkmasking:
  vel: 3200. # velocity
  fmax: 70 # maximum frequency
  critical: 1.00 # scaling to be applied to the f=k*v line used to create the mask
  koffset: 0.002 # shift to be applied to the f=k*v line used to create the mask

slopeestimation:
  eps_slopeest: 1000 # regularization factor for smoothing
  niter_slopeest: 200 # number of iterations of lsqr

interpolation:
  use_secondder: False # use first+second order derivative (True) or just first derivative (False) for interpolation
  eps_slopes: 10 # regularization factor for slope consistency term
  eps_fk: 0.001 # regularization factor for sparsity term
  niter: 200 # number of iterations of fista